openapi: 3.2.0
info:
  title: Tm Forum Import Job API
  version: '1.0'
  description: 'Operations tagged importJob across 3 of this provider''s published API definitions: tm-forum-tmf620-product-catalog-openapi.yaml, tm-forum-tmf633-service-catalog-openapi.json, tm-forum-tmf634-resource-catalog-openapi.json. Each path carries the servers of the definition it was published in.'
servers:
- url: https://serverRoot/productCatalogManagement/v5/
- url: https://serverRoot/tmf-api/serviceCatalogManagement/v4/
- url: https://serverRoot/tmf-api/resourceCatalog/v4/
tags:
- name: importJob
  description: Operations for ImportJob Resource
paths:
  /importJob:
    get:
      tags:
      - importJob
      summary: TM Forum List or Find ImportJob Objects
      description: List or find ImportJob objects
      operationId: listImportJob
      parameters:
      - $ref: '#/components/parameters/Fields'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          $ref: '#/components/responses/200ImportJobArray'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '500':
          $ref: '#/components/responses/500'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'
    post:
      tags:
      - importJob
      summary: TM Forum Creates a ImportJob
      description: This operation creates a ImportJob entity.
      operationId: createImportJob
      parameters:
      - $ref: '#/components/parameters/Fields'
      requestBody:
        $ref: '#/components/requestBodies/ImportJob_FVO'
      responses:
        '201':
          $ref: '#/components/responses/201ImportJob'
        '202':
          description: Accepted
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'
    servers:
    - url: https://serverRoot/productCatalogManagement/v5/
  /importJob/{id}:
    get:
      tags:
      - importJob
      summary: TM Forum Retrieves a ImportJob by ID
      description: This operation retrieves a ImportJob entity. Attribute selection enabled for all first level attributes.
      operationId: retrieveImportJob
      parameters:
      - $ref: '#/components/parameters/Id'
      - $ref: '#/components/parameters/Fields'
      responses:
        '200':
          $ref: '#/components/responses/200ImportJob_Get'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '500':
          $ref: '#/components/responses/500'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'
    delete:
      tags:
      - importJob
      summary: TM Forum Deletes a ImportJob
      description: This operation deletes a ImportJob entity.
      operationId: deleteImportJob
      parameters:
      - $ref: '#/components/parameters/Id'
      responses:
        '202':
          $ref: '#/components/responses/202'
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'
    servers:
    - url: https://serverRoot/productCatalogManagement/v5/
components:
  schemas:
    Error:
      discriminator:
        propertyName: '@type'
        mapping:
          Error: '#/components/schemas/Error'
      allOf:
      - $ref: '#/components/schemas/Extensible'
      - type: object
        required:
        - code
        - reason
        properties:
          code:
            type: string
            description: Application relevant detail, defined in the API or a common list.
          reason:
            type: string
            description: Explanation of the reason for the error which can be shown to a client user.
          message:
            type: string
            description: More details and corrective actions related to the error which can be shown to a client user.
          status:
            type: string
            description: HTTP Error code extension
          referenceError:
            type: string
            description: URI of documentation describing the error.
      description: Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
    ImportJob_FVO:
      allOf:
      - $ref: '#/components/schemas/Entity_FVO'
      - type: object
        description: Represents a task used to import resources from a file
        properties:
          completionDate:
            type: string
            format: date-time
            description: Date at which the job was completed
          contentType:
            type: string
            description: Indicates the format of the imported data
          creationDate:
            type: string
            format: date-time
            description: Date at which the job was created
          errorLog:
            type: string
            description: Path to file or stream where errors encountered during the job processing can be written
          path:
            type: string
            description: URL of the root resource where the content of the file specified by the import job must be applied
          status:
            $ref: '#/components/schemas/JobStateType'
          url:
            type: string
            format: uri
            description: URL of the file containing the data to be imported
          id:
            type: string
            description: unique identifier for import job
        required:
        - url
      discriminator:
        propertyName: '@type'
        mapping:
          ImportJob: '#/components/schemas/ImportJob_FVO'
    Entity:
      type: object
      description: Base entity schema for use in TMForum Open-APIs. Property.
      allOf:
      - $ref: '#/components/schemas/Extensible'
      - $ref: '#/components/schemas/Addressable'
    Extensible:
      type: object
      description: Base Extensible schema for use in TMForum Open-APIs - When used for in a schema it means that the Entity described by the schema  MUST be extended with the @type
      properties:
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class Extensible name
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class
        '@schemaLocation':
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
      required:
      - '@type'
    Entity_FVO:
      type: object
      description: Base entity schema for use in TMForum Open-APIs. Property.
      allOf:
      - $ref: '#/components/schemas/Extensible_FVO'
      - $ref: '#/components/schemas/Addressable_FVO'
    Extensible_FVO:
      type: object
      description: Base Extensible schema for use in TMForum Open-APIs - When used for in a schema it means that the Entity described by the schema  MUST be extended with the @type
      properties:
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class Extensible name
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class
        '@schemaLocation':
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
      required:
      - '@type'
    Addressable:
      type: object
      description: Base schema for adressable entities
      properties:
        href:
          type: string
          description: Hyperlink reference
        id:
          type: string
          description: unique identifier
    Addressable_FVO:
      type: object
      description: Base schema for adressable entities
      properties:
        id:
          type: string
          description: unique identifier
    JobStateType:
      enum:
      - Not Started
      - Running
      - Succeeded
      - Failed
      type: string
      description: Valid values for the state of a batch job (e.g. catalog import)
    ImportJob:
      allOf:
      - $ref: '#/components/schemas/Entity'
      - type: object
        description: Represents a task used to import resources from a file
        properties:
          completionDate:
            type: string
            format: date-time
            description: Date at which the job was completed
          contentType:
            type: string
            description: Indicates the format of the imported data
          creationDate:
            type: string
            format: date-time
            description: Date at which the job was created
          errorLog:
            type: string
            description: Path to file or stream where errors encountered during the job processing can be written
          path:
            type: string
            description: URL of the root resource where the content of the file specified by the import job must be applied
          status:
            $ref: '#/components/schemas/JobStateType'
          url:
            type: string
            format: uri
            description: URL of the file containing the data to be imported
          id:
            type: string
            description: unique identifier for import job
      discriminator:
        propertyName: '@type'
        mapping:
          ImportJob: '#/components/schemas/ImportJob'
    ImportJob_2:
      type: object
      description: Represents a task used to import resources from a file
      properties:
        id:
          type: string
          description: Identifier of the import job
        href:
          type: string
          format: uri
          description: Reference of the import job
        completionDate:
          type: string
          format: date-time
          description: Date at which the job was completed
        contentType:
          type: string
          description: Indicates the format of the imported data
        creationDate:
          type: string
          format: date-time
          description: Date at which the job was created
        errorLog:
          type: string
          description: Reason for failure if status is failed
        path:
          type: string
          description: URL of the root resource where the content of the file specified by the import job must be applied
        url:
          type: string
          format: uri
          description: URL of the file containing the data to be imported
        status:
          $ref: '#/components/schemas/JobStateType'
          description: Status of the import job (not started, running, succeeded, failed)
    Error_2:
      description: Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
      type: object
      required:
      - code
      - reason
      properties:
        code:
          type: string
          description: Application relevant detail, defined in the API or a common list.
        reason:
          type: string
          description: Explanation of the reason for the error which can be shown to a client user.
        message:
          type: string
          description: More details and corrective actions related to the error which can be shown to a client user.
        status:
          type: string
          description: HTTP Error code extension
        referenceError:
          type: string
          format: uri
          description: URI of documentation describing the error.
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class.
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name.
    ImportJob_Create:
      type: object
      description: 'Represents a task used to import resources from a file

        Skipped properties: id,href'
      required:
      - url
      properties:
        completionDate:
          type: string
          format: date-time
          description: Date at which the job was completed
        contentType:
          type: string
          description: Indicates the format of the imported data
        creationDate:
          type: string
          format: date-time
          description: Date at which the job was created
        errorLog:
          type: string
          description: Reason for failure if status is failed
        path:
          type: string
          description: URL of the root resource where the content of the file specified by the import job must be applied
        url:
          type: string
          format: uri
          description: URL of the file containing the data to be imported
        status:
          $ref: '#/components/schemas/JobStateType'
          description: Status of the import job (not started, running, succeeded, failed)
    ImportJob_3:
      type: object
      description: Represents a task used to import resources from a file
      properties:
        id:
          type: string
          description: Identifier of the import job
        href:
          type: string
          description: Reference of the import job
        completionDate:
          type: string
          format: date-time
          description: Date at which the job was completed
        contentType:
          type: string
          description: Indicates the format of the imported data
        creationDate:
          type: string
          format: date-time
          description: Date at which the job was created
        errorLog:
          type: string
          description: Reason for failure if status is failed
        path:
          type: string
          description: URL of the root resource where the content of the file specified by the import job must be applied
        url:
          type: string
          description: URL of the file containing the data to be imported
        status:
          $ref: '#/components/schemas/JobStateType'
          description: Status of the import job (not started, running, succeeded, failed)
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name
    Error_3:
      description: Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
      type: object
      required:
      - code
      - reason
      properties:
        code:
          type: string
          description: Application relevant detail, defined in the API or a common list.
        reason:
          type: string
          description: Explanation of the reason for the error which can be shown to a client user.
        message:
          type: string
          description: More details and corrective actions related to the error which can be shown to a client user.
        status:
          type: string
          description: HTTP Error code extension
        referenceError:
          type: string
          format: uri
          description: URI of documentation describing the error.
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class.
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name.
    ImportJob_Create_2:
      type: object
      description: 'Represents a task used to import resources from a file

        Skipped properties: id,href'
      required:
      - url
      properties:
        completionDate:
          type: string
          format: date-time
          description: Date at which the job was completed
        contentType:
          type: string
          description: Indicates the format of the imported data
        creationDate:
          type: string
          format: date-time
          description: Date at which the job was created
        errorLog:
          type: string
          description: Reason for failure if status is failed
        path:
          type: string
          description: URL of the root resource where the content of the file specified by the import job must be applied
        url:
          type: string
          description: URL of the file containing the data to be imported
        status:
          $ref: '#/components/schemas/JobStateType'
          description: Status of the import job (not started, running, succeeded, failed)
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name
  responses:
    200ImportJobArray:
      description: Success
      headers:
        X-Total-Count:
          $ref: '#/components/headers/X-Total-Count'
        X-Result-Count:
          $ref: '#/components/headers/X-Result-Count'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ImportJob'
          examples:
            ImportJob_list_example:
              $ref: '#/components/examples/ImportJob_list_example_response'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    201ImportJob:
      description: OK/Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImportJob'
          examples:
            Import_Job_Create_example:
              $ref: '#/components/examples/Import_Job_Create_example_response'
    '405':
      description: Method Not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '501':
      description: Not Implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    200ImportJob_Get:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImportJob'
          examples:
            ImportJob_retrieve_example:
              $ref: '#/components/examples/ImportJob_retrieve_example_response'
    '202':
      description: Accepted
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '204':
      description: Deleted
  requestBodies:
    ImportJob_FVO:
      description: The ImportJob to be created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImportJob_FVO'
          examples:
            Import_Job_Create_example:
              $ref: '#/components/examples/Import_Job_Create_example_request'
      required: true
  parameters:
    Fields:
      name: fields
      in: query
      description: Comma-separated properties to be provided in response
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: Requested number of resources to be provided in response
      schema:
        type: integer
    Id:
      name: id
      required: true
      schema:
        type: string
      in: path
      description: Identifier of the Resource
    Offset:
      name: offset
      in: query
      description: Requested index for start of resources to be provided in response
      schema:
        type: integer
  examples:
    Import_Job_Create_example_request:
      value:
        contentType: application/json
        path: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/
        url: ftp://ftp.mycsp.com/productCatalogManagement/1877.json
        '@type': ImportJob
      description: Here is an example of a request for creating an import job.
    Import_Job_Create_example_response:
      value:
        id: '2341'
        href: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/importJob/2341
        contentType: application/json
        creationDate: '2020-08-25T00:00:00Z'
        completionDate: '2020-08-25T00:01:31Z'
        path: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/
        status: Succeeded
        url: ftp://ftp.mycsp.com/productCatalogManagement/1877.json
        errorLog: http://my-platform/logging/errors.log
        '@type': ImportJob
      description: Here is an example of a response for creating an import job.
    ImportJob_retrieve_example_response:
      value:
        id: '2341'
        href: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/importJob/2341
        contentType: application/json
        creationDate: '2020-08-25T00:00:00Z'
        completionDate: '2020-08-25T00:01:31Z'
        path: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/
        status: Succeeded
        url: ftp://ftp.mycsp.com/productCatalogManagement/1866.json
        errorLog: http://my-platform/logging/errors.log
        '@type': ImportJob
      description: Here is an example of a request for retrieving a specific import job.
    ImportJob_list_example_response:
      value:
      - id: '2340'
        href: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/importJob/2340
        contentType: application/json
        creationDate: '2020-08-25T00:00:00Z'
        completionDate: '2020-08-25T00:00:19Z'
        path: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/Catalog/
        status: Failed
        url: ftp://ftp.mycsp.com/productCatalogManagement/2544.json
        errorLog: http://my-platform/logging/errors.log
        '@type': ImportJob
      - id: '2341'
        href: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/importJob/2341
        contentType: application/json
        creationDate: '2020-08-25T00:00:00Z'
        completionDate: '2020-08-25T00:01:31Z'
        path: https://mycsp.com:8080/tmf-api/productCatalogManagement/v5/
        status: Succeeded
        url: ftp://ftp.mycsp.com/productCatalogManagement/1877.json
        errorLog: ''
        '@type': ImportJob
      description: Here is an example of a request for retrieving multiple import jobs.
  headers:
    X-Result-Count:
      description: Actual number of items returned in the response body
      schema:
        type: integer
    X-Total-Count:
      description: Total number of items matching criteria
      schema:
        type: integer
x-refined-from:
- tm-forum-tmf620-product-catalog-openapi.yaml
- tm-forum-tmf633-service-catalog-openapi.json
- tm-forum-tmf634-resource-catalog-openapi.json
